---
title: "Activity 2.5 - Exploratory Data Analysis: Data Visualizations - Customization"
author: "Purple"
date: "09/19/2019"
output: 
  html_document: 
    keep_md: yes
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse)
library(gapminder)
```

### Load data

```{r load-data, message=FALSE}
my_gm <- gapminder
```

```{r gdp-lifeExp-canvas, message = FALSE}
my_gm %>% 
  filter(year == "2007",
         continent != "Oceania") %>% 
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  scale_x_log10() + 
  geom_point() +
  facet_wrap(~ continent)
```

  

### Exercise 1

```{r}
p <- my_gm %>% 
  filter(year == "2007",
         continent != "Oceania") %>% 
  ggplot(aes(x = gdpPercap, y = lifeExp, color = continent)) +
  scale_x_log10() + 
  geom_point() +
  facet_wrap(~ continent) +
  theme_dark()

p + labs(title = "GDP Per Capita vs Life Expectancy by Continent") +
  xlab("GDP per capita") +
  ylab("Life Expectancy")
```

### Exercise 2

```{r}
p <- my_gm %>% 
  filter(year == "2007",
         continent != "Oceania") %>% 
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  scale_x_log10() + 
  geom_point() +
  facet_wrap(~ continent)

p + labs(title = "GDP Per Capita vs Life Expectancy by Continent") +
  xlab("GDP per capita") +
  ylab("Life Expectancy")
```

### Exercise 3

...


### Exercise 4

...

